{{- if eq (include "gitlab-runner.isSessionServerAllowed" . ) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gitlab-runner.fullname" . }}-session-server
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: {{ default .Release.Namespace .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gitlab-runner.fullname" . }}-session-server
subjects:
- kind: ServiceAccount
  name: {{ include "gitlab-runner.serviceAccountName" . }}
  namespace: "{{ default .Release.Namespace .Values.namespace }}"
{{- end -}}
