{{- $configureIngressCertmanager := (pluck "configureCertmanager" .Values.global.ingress (dict "configureCertmanager" false) | first) }}
{{- $configureGatewayCertmanager := .Values.global.gatewayApi.configureCertmanager }}
{{- if or $configureGatewayCertmanager $configureIngressCertmanager }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-certmanager
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
data:
  create-issuer: |
    {{- .Files.Get "files/create_issuer.sh" | indent 4 }}
  {{- if $configureIngressCertmanager }}
  issuer.yml: |
     {{- include (print $.Template.BasePath "/_issuer.yaml") . | indent 4 }}
  {{- end }}
  {{- if $configureGatewayCertmanager }}
  gateway_issuer.yaml: |
    {{- include (print $.Template.BasePath "/_gateway_issuer.yaml") . | indent 4 }}
  {{- end }}
{{ end }}