apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/vreve/Helm-test-argocd.git'
    targetRevision: main
    path: gitlab-argocd/charts/gitlab
    helm:
      valueFiles:
        - ../values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab   # namespace f√∂r GitLab i klustret

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
