global:
  edition: ce
  hosts:
    domain: "local.test"
  ingress:
    configureCertmanager: false

# St√§ng av alla extra subcharts
certmanager:
  install: true        # installera cert-manager
  installCRDs: true    # installera CRDs
  nameOverride: certmanager

certmanager-issuer:
  email: email@example.com

nginx-ingress:
  enabled: false

gitlab-runner:
  install: false

registry:
  install: false

minio:
  install: false

postgresql:
  install: false

redis:
  install: false

prometheus:
  install: false
