global:
  edition: ce
  hosts:
    domain: "local.test"
  ingress:
    configureCertmanager: false

installCertmanager: true

certmanager:
  installCRDs: true
  nameOverride: certmanager

certmanager-issuer:
  install: true        # m√•ste finnas
  email: test@example.com

nginx-ingress:
  enabled: false

gitlab-runner:
  install: false

registry:
  install: false

minio:
  install: false

postgresql:
  install: false

redis:
  install: false

prometheus:
  install: false
