apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vreve/Helm-test-argocd.git'
    targetRevision: main
    path: gitlab-argocd/charts/gitlab
    helm:
      valueFiles:
        - gitlab-argocd/charts/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
